"""
=========================================================
Module Name : report_generator.py
Purpose     : Generate the AI Market Intelligence HTML report
Author      : AI Market Intelligence Platform
Version     : 3.1
=========================================================
"""

from pathlib import Path
from datetime import datetime

from jinja2 import Environment, FileSystemLoader

from reports.report_data_builder import build_report_data


def generate_report(trend_report):
    """
    Generate the HTML AI Market Intelligence Report.

    Args:
        trend_report (dict): Trend analysis generated by the analyzer.

    Returns:
        Path: Path to the generated HTML report.
    """

    # --------------------------------------------------
    # Build Report Data
    # --------------------------------------------------

    report_data = build_report_data(trend_report)

    report_data["generated_date"] = datetime.now().strftime(
        "%d %B %Y %I:%M %p"
    )

    # --------------------------------------------------
    # Project Paths
    # --------------------------------------------------

    reports_dir = Path(__file__).parent
    templates_dir = reports_dir / "templates"
    static_dir = reports_dir / "static"
    output_dir = reports_dir / "output"

    output_dir.mkdir(exist_ok=True)

    # --------------------------------------------------
    # Read CSS File
    # --------------------------------------------------

    css_path = static_dir / "styles.css"

    if not css_path.exists():
        raise FileNotFoundError(
            f"styles.css not found:\n{css_path}"
        )

    with open(css_path, "r", encoding="utf-8") as f:
        css = f.read()

    embedded_css = f"<style>\n{css}\n</style>"

    print(f"✓ CSS Loaded ({len(css)} characters)")

    # --------------------------------------------------
    # Load Jinja2 Template
    # --------------------------------------------------

    env = Environment(
        loader=FileSystemLoader(str(templates_dir)),
        autoescape=True
    )

    template = env.get_template("report.html")

    # --------------------------------------------------
    # Render HTML
    # --------------------------------------------------

    html = template.render(
        **report_data,
        embedded_css=embedded_css
    )

    print("✓ HTML Rendered")

    # --------------------------------------------------
    # Verify CSS was Embedded
    # --------------------------------------------------

    if "<style>" in html:
        print("✓ CSS Embedded Successfully")
    else:
        print("❌ CSS NOT Embedded")

    # --------------------------------------------------
    # Save Report
    # --------------------------------------------------

    output_file = output_dir / "ai_market_report.html"

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(html)

    print("\n=====================================")
    print("HTML Report Generated Successfully")
    print(output_file)
    print("=====================================")

    return output_file